uses: google/secrets-sync-action@[insert version or commit]
  with:
    SECRETS: |
      ^AZURE_CLIENT_ID_DEV
      ^AZURE_TENANT_ID
    REPOSITORIES: |
      ${{github.repository}}
    DRY_RUN: true
    GITHUB_TOKEN: ${{ secrets.SECRET_SYNC_TOKEN }}
    GITHUB_API_URL: ${{ secrets.CUSTOM_GITHUB_API_URL }}
    CONCURRENCY: 10
  env:
    FOO: ${{github.run_id}}
    FOOBAR: BAZ
