
on:
 workflow_dispatch:
 
 uses: google/secrets-sync-action@v1.4.1
  with:
    SECRETS: |
     ^AZURE_CLIENT_ID_DEV
     ^AZURE_TENANT_ID
    REPOSITORIES: |
      ${{github.repository}}
    DRY_RUN: true
    GITHUB_TOKEN: ${{ secrets.SECRET_SYNC_TOKEN }}
    GITHUB_API_URL: ${{ secrets.CUSTOM_GITHUB_API_URL }}
    CONCURRENCY: 10
    
  env:
    AZURE_CLIENT_ID_DEV: ${{ secrets.AZURE_CLIENT_ID_DEV }}
    AZURE_SUBSCRIPTION_ID_DEV: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
