on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create file
      run: |
        printf "Hello\nWorld\n" > hw.txt
        
    - name: Commit & Push
      uses: Andro999b/push@v1.3
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: master
         force: true
         message: 'Overwritten by Github Actions - ${date}'
      
