on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create file
      run: |
        printf "Hello\nWorld\neasdfadfdf" > hw.txt
        
    - name: Commit & Push
      run: |
        git config --local user.email "kevinm@korbicom.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m 'Kevins message'
        git push -u origin master

      
