on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create file
      run: |
        printf "Hello\nWorld\n" > hw.txt
        
    - name: Commit & Push
      run: |
        git commit master
        git push master
      
