name: Get version

on:
  workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        
         - name: Checkout
           uses: actions/checkout@v2
            
         - name: Read Json File
           id: json_properties
           uses: zoexx/github-action-json-file-properties@release
           with:
            file_path: ".github/workflows/package.json"
         - run: |
             echo "BUILD=${{ steps.json_properties.outputs.Build }}" >> $GITHUB_ENV
             echo "MAJOR=${{ steps.json_properties.outputs.Major }}" >> $GITHUB_ENV
             echo "MINOR=${{ steps.json_properties.outputs.Minor }}" >> $GITHUB_ENV
              
         - name: Test
           run: |
             echo $BUILD
             echo $MAJOR
             echo $MINOR
           
         - name: Autoincrement a new major version
           run: |
             echo "NEW_MAJOR_VERSION=$((${{ env.MAJOR }}+1))" >> $GITHUB_ENV
             
         - name: Test
           run: |
             echo $MAJOR
             echo $NEW_MAJOR_VERSION    

         - name: Update my-file.json description
           uses: jossef/action-set-json-field@v2.1
           with:
            file: .github/workflows/package.json
            field: Major
            value: "$NEW_MAJOR_VERSION"      
            
         - name: Commit & Push
           run: |
            git config --local user.email "kevinm@korbicom.com"
            git config --local user.name "GitHub Action"
            git commit -m 'Update json'
            git push origin master  
    
