name: Get version

on:
  workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        
         - name: Checkout
           uses: actions/checkout@v2
            
         - name: Read Json File
           id: json_properties
           uses: zoexx/github-action-json-file-properties@release
           with:
            file_path: ".github/workflows/package.json"
         - run: echo "VERSION=${{ steps.json_properties.outputs.version }}" >> $GITHUB_ENV
              
         - name: Test
           run: echo $VERSION
           
         - name: Parse version string
           id: semver_parser 
           uses: booxmedialtd/ws-action-parse-semver@v1
           with:
            input_string: "$VERSION"
        
         - name: Use version string
           run: | 
               echo "v${{ steps.semver_parser.outputs.major }}"
               echo "v${{ steps.semver_parser.outputs.minor }}"
               echo "v${{ steps.semver_parser.outputs.patch }}"
               echo "v${{ steps.semver_parser.outputs.prerelease }}"
               echo "v${{ steps.semver_parser.outputs.build }}"
               echo "v${{ steps.semver_parser.outputs.fullversion }}"           
