on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: cooth
          github_token: ${{ secrets.GITHUB_TOKEN }}
