on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      
      - name: Run some git commands
        run: |
         git tag -a v1.4 -m "my version 1.4"
         
