name: Create Release

on:
  push:
    branches:
      - master
jobs:
  create-release:
    runs-on: ubuntu-latest
    if: contains( github.event.head_commit.message, 'release' )
    steps:
     - name: Create Release Notes File
       env: 
        COMMITTEXT: "${{ github.event.head_commit.message }}"
       run: |
          echo This demo file shows a 
          echo very basic and easy-to-understand workflow.          
     - name: Create Tag
       uses: actions/github-script@v3
       env:
          TAG: 'Mytag5'
       with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
             ref: "refs/tags/Mytag5",
              sha: context.sha
            })
     - name: Create Release
       id: create_release
       uses: actions/create-release@latest
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
           tag_name: ${{ github.ref }}
           release_name: Release ${{ github.ref }}
           body: |
             ${{ steps.Changelog.outputs.changelog }}
           draft: false
           prerelease: false       
          

          
