on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub action'
      - uses: actions/checkout@v2
      
      - name: 'Create tag'
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: cooth
          
